/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.CmModelo;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.event.ListSelectionListener;
import Mains.mainUsuarios;
import Mains.mainVuelos;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import Vista.VistaLogin;
import java.util.List;

import javax.swing.event.ListSelectionEvent;
import javax.swing.*;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionListener;

/**
 *
 * @author itzel
 */
public class vistaPag extends javax.swing.JFrame {
    //private String correo;
    /**
     * Creates new form panemuestra
     */
    private CmModelo modelo;
    public vistaPag() {   
        
        initComponents();
        agregarListenerTabla();
        btnSiguiente.setEnabled(false);
        customizeButton(btnBuscar);
        customizeButton(btnCrudUs);
        customizeButton(btnCrudVuelos);
        customizeButton(btnSiguiente);
        //customizeButton(jButton1);
        jPanel14.setVisible(false);
        modelo =new CmModelo();   
        

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelReserva = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelUs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPanePublicidad = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelAnun = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelqn = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jScrollPaneReserva = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jPanelAnun1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jScrollPaneBoleto = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jPanelAnun2 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblOrigen2 = new javax.swing.JLabel();
        lblDestino2 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblVuelo = new javax.swing.JLabel();
        lblHora2 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        cboAsientos = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPaneAdmin = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanelAnun3 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        btnCrudUs = new javax.swing.JButton();
        btnCrudVuelos = new javax.swing.JButton();
        jLabel104 = new javax.swing.JLabel();
        btnMostrarGraficos = new javax.swing.JButton();
        cboMes = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnMostrarGraficoPorMes = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPaneInfo = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jPanelAnun4 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jlabelTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 310, 60));

        jPanel3.setBackground(new java.awt.Color(42, 140, 130));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/plano-alt.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MI VUELO");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(89, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(76, 76, 76)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 60));

        jPanelReserva.setBackground(new java.awt.Color(42, 140, 130));
        jPanelReserva.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelReservaMouseMoved(evt);
            }
        });
        jPanelReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelReservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelReservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelReservaMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/reserva (2).png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RESERVAR");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanelReservaLayout = new javax.swing.GroupLayout(jPanelReserva);
        jPanelReserva.setLayout(jPanelReservaLayout);
        jPanelReservaLayout.setHorizontalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(78, 78, 78))
        );
        jPanelReservaLayout.setVerticalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanelReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 60));

        jPanel14.setBackground(new java.awt.Color(42, 140, 130));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/equipo-de-usuario (1).png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMINISTRACIÓN");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(11, 11, 11))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, 60));

        jLabelSalir.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSalir.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/marca-x-rectangular.png"))); // NOI18N
        jLabelSalir.setText("Cerrar sesión");
        jLabelSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 150, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText(".");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel1.setBackground(new java.awt.Color(42, 140, 130));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 480));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/hombre (2).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 130));

        jLabelUs.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabelUs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUs.setText("Admin");
        jPanel1.add(jLabelUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(39, 89, 80));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1490, 80));

        jLabel2.setBackground(new java.awt.Color(39, 89, 80));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, 120));

        jScrollPanePublicidad.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPanePublicidad.setBorder(null);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/mapa_nuevo.png"))); // NOI18N
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, -1, -1));

        jPanelAnun.setBackground(new java.awt.Color(39, 89, 80));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Síguenos en redes sociales");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N

        jLabelqn.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabelqn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelqn.setText("¿Quiénes somos?");
        jLabelqn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelqnMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" Términos y condiciones");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("|");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("|");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("|");

        jLabel22.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Aviso de privacidad");

        jLabel23.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Contrato");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("|");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/instagram.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnunLayout = new javax.swing.GroupLayout(jPanelAnun);
        jPanelAnun.setLayout(jPanelAnunLayout);
        jPanelAnunLayout.setHorizontalGroup(
            jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnunLayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnunLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnunLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanelAnunLayout.createSequentialGroup()
                .addGroup(jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnunLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel16))
                    .addGroup(jPanelAnunLayout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnunLayout.createSequentialGroup()
                    .addContainerGap(836, Short.MAX_VALUE)
                    .addComponent(jLabelqn)
                    .addGap(36, 36, 36)))
        );
        jPanelAnunLayout.setVerticalGroup(
            jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnunLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(22, 22, 22)
                .addGroup(jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanelAnunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnunLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabelqn)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel10.add(jPanelAnun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1170, 1000, 220));

        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/el-verano.png"))); // NOI18N
        jPanel10.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -10, 560, 520));

        jScrollPanePublicidad.setViewportView(jPanel10);

        jTabbedPane1.addTab("tab3", jScrollPanePublicidad);

        jScrollPaneReserva.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneReserva.setBorder(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("ORIGEN");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        cbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrigenActionPerformed(evt);
            }
        });
        jPanel11.add(cbOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, -1));

        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoActionPerformed(evt);
            }
        });
        jPanel11.add(cbDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("DESTINO");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID vuelo", "Origen", "Destino", "Precio ", "Fecha", "Hora", "Disposicion"
            }
        ));
        jScrollPane3.setViewportView(tablaVuelos);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 650, 290));

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel11.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 120, 100, -1));

        jPanelAnun1.setBackground(new java.awt.Color(39, 89, 80));

        jLabel27.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Síguenos en redes sociales");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("¿Quiénes somos?");

        jLabel30.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" Términos y condiciones");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("|");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("|");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("|");

        jLabel34.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Aviso de privacidad");

        jLabel35.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Contrato");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("|");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/instagram.png"))); // NOI18N
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnun1Layout = new javax.swing.GroupLayout(jPanelAnun1);
        jPanelAnun1.setLayout(jPanelAnun1Layout);
        jPanelAnun1Layout.setHorizontalGroup(
            jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun1Layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addGroup(jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun1Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanelAnun1Layout.createSequentialGroup()
                .addGroup(jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnun1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel27))
                    .addGroup(jPanelAnun1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel37)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun1Layout.createSequentialGroup()
                    .addContainerGap(846, Short.MAX_VALUE)
                    .addComponent(jLabel29)
                    .addGap(36, 36, 36)))
        );
        jPanelAnun1Layout.setVerticalGroup(
            jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnun1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(22, 22, 22)
                .addGroup(jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanelAnun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnun1Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel29)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanelAnun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1170, 1010, 220));

        btnSiguiente.setBackground(new java.awt.Color(204, 255, 255));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel11.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 160, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/equipaje.png"))); // NOI18N
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 270, 250));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/viaje (1).png"))); // NOI18N
        jPanel11.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 300, 220));

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/viaje.png"))); // NOI18N
        jPanel11.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 500, 330));

        jScrollPaneReserva.setViewportView(jPanel11);

        jTabbedPane1.addTab("tab3", jScrollPaneReserva);

        jScrollPaneBoleto.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneBoleto.setBorder(null);
        jScrollPaneBoleto.setPreferredSize(new java.awt.Dimension(1000, 1500));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(1000, 1500));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAnun2.setBackground(new java.awt.Color(39, 89, 80));

        jLabel40.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Síguenos en redes sociales");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("¿Quiénes somos?");

        jLabel43.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(" Términos y condiciones");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("|");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("|");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("|");

        jLabel47.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Aviso de privacidad");

        jLabel48.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Contrato");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("|");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/instagram.png"))); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnun2Layout = new javax.swing.GroupLayout(jPanelAnun2);
        jPanelAnun2.setLayout(jPanelAnun2Layout);
        jPanelAnun2Layout.setHorizontalGroup(
            jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun2Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun2Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun2Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanelAnun2Layout.createSequentialGroup()
                .addGroup(jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnun2Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel40))
                    .addGroup(jPanelAnun2Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel50)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun2Layout.createSequentialGroup()
                    .addContainerGap(836, Short.MAX_VALUE)
                    .addComponent(jLabel42)
                    .addGap(36, 36, 36)))
        );
        jPanelAnun2Layout.setVerticalGroup(
            jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnun2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addGap(22, 22, 22)
                .addGroup(jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanelAnun2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnun2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel42)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel12.add(jPanelAnun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1270, 1000, 230));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(9, 69, 63));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel39.setText("ViajesITOs");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 6, -1, 28));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel51.setText("Pase de Abordar");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 6, -1, 28));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel52.setText("Pase de Abordar");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 6, -1, 28));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/aeronave.png"))); // NOI18N
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 69));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("NOMBRE");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("APELLIDO");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 118, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setText("DESTINO");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setText("ORIGEN");
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("FECHA");
        jPanel6.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 187, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("HORA");
        jPanel6.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 235, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("ASIENTO");
        jPanel6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 118, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("VUELO");
        jPanel6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 187, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setText("DESTINO");
        jPanel6.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setText("SALIDA");
        jPanel6.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("FECHA");
        jPanel6.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("HORA");
        jPanel6.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(6, 69, 63));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel67.setText("ViajesITOs");
        jPanel6.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 209, -1, 28));

        jPanel8.setBackground(new java.awt.Color(9, 69, 63));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, 1000, -1));

        jPanel9.setBackground(new java.awt.Color(9, 69, 63));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel68.setText("ViajesITOs");
        jPanel9.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 6, -1, 28));

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel69.setText("Pase de Abordar");
        jPanel9.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 6, -1, 28));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/aeronave.png"))); // NOI18N
        jPanel9.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, 1000, 64));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(6, 69, 63));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel71.setText("ViajesITOs");
        jPanel6.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 467, -1, 28));

        jPanel13.setBackground(new java.awt.Color(9, 69, 63));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 572, 1000, -1));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/seguro-de-viaje.png"))); // NOI18N
        jPanel6.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 624, -1, -1));

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/seguro-de-viaje.png"))); // NOI18N
        jPanel6.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 75, -1, -1));
        jPanel6.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 140, 173, 20));
        jPanel6.add(lblOrigen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 220, 130, 20));
        jPanel6.add(lblDestino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 270, 130, 20));
        jPanel6.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 143, 20));
        jPanel6.add(lblVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 209, 103, 20));
        jPanel6.add(lblHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 103, 20));

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/boleto.png"))); // NOI18N
        jPanel6.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 250, 200));

        cboAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAsientosActionPerformed(evt);
            }
        });
        jPanel6.add(cboAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 140, 30));

        btnFinalizar.setBackground(new java.awt.Color(0, 153, 153));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel6.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, 40));
        jPanel6.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, 123, 20));
        jPanel6.add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, 103, 20));
        jPanel6.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 103, 20));
        jPanel6.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 251, 103, 20));
        jPanel6.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 209, 143, 20));

        btnCancelar.setBackground(new java.awt.Color(0, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Salir");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 160, 40));

        jPanel12.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 610));

        jScrollPaneBoleto.setViewportView(jPanel12);

        jTabbedPane1.addTab("tab3", jScrollPaneBoleto);
        jScrollPaneBoleto.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        jScrollPaneAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneAdmin.setBorder(null);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAnun3.setBackground(new java.awt.Color(39, 89, 80));

        jLabel79.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Síguenos en redes sociales");

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N

        jLabel81.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("¿Quiénes somos?");

        jLabel82.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText(" Términos y condiciones");

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("|");

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("|");

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("|");

        jLabel86.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Aviso de privacidad");

        jLabel87.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Contrato");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("|");

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/instagram.png"))); // NOI18N
        jLabel89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel89MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnun3Layout = new javax.swing.GroupLayout(jPanelAnun3);
        jPanelAnun3.setLayout(jPanelAnun3Layout);
        jPanelAnun3Layout.setHorizontalGroup(
            jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun3Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun3Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun3Layout.createSequentialGroup()
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel82)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanelAnun3Layout.createSequentialGroup()
                .addGroup(jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnun3Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel79))
                    .addGroup(jPanelAnun3Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel89)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun3Layout.createSequentialGroup()
                    .addContainerGap(836, Short.MAX_VALUE)
                    .addComponent(jLabel81)
                    .addGap(36, 36, 36)))
        );
        jPanelAnun3Layout.setVerticalGroup(
            jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnun3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel89)
                .addGap(22, 22, 22)
                .addGroup(jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel86)
                    .addComponent(jLabel87)
                    .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanelAnun3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnun3Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel81)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel15.add(jPanelAnun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1270, 1000, 230));

        btnCrudUs.setText("CRUD USUARIOS");
        btnCrudUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudUsActionPerformed(evt);
            }
        });
        jPanel15.add(btnCrudUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, 60));

        btnCrudVuelos.setText("CRUD VUELOS");
        btnCrudVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrudVuelosMouseClicked(evt);
            }
        });
        btnCrudVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudVuelosActionPerformed(evt);
            }
        });
        jPanel15.add(btnCrudVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 210, 60));

        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/ajuste.png"))); // NOI18N
        jPanel15.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 520, 430));

        btnMostrarGraficos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrarGraficos.setText("Mostrar Grafico Completo");
        btnMostrarGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGraficosActionPerformed(evt);
            }
        });
        jPanel15.add(btnMostrarGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 180, 50));

        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel15.add(cboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Mostrar graficos por mes:");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 250, 30));

        btnMostrarGraficoPorMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrarGraficoPorMes.setText("Mostrar Grafico Por Mes");
        jPanel15.add(btnMostrarGraficoPorMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 170, 50));

        jLabel12.setText("Seleccione el mes:");
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, -1, -1));

        jScrollPaneAdmin.setViewportView(jPanel15);

        jTabbedPane1.addTab("tab3", jScrollPaneAdmin);

        jScrollPaneInfo.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneInfo.setBorder(null);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAnun4.setBackground(new java.awt.Color(39, 89, 80));

        jLabel90.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Síguenos en redes sociales");

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/AEM-completo-negro-blanco.png"))); // NOI18N

        jLabel92.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("¿Quiénes somos?");

        jLabel93.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText(" Términos y condiciones");

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("|");

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("|");

        jLabel96.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("|");

        jLabel97.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("Aviso de privacidad");

        jLabel98.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("Contrato");

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("|");

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aerolinea/imagenes/instagram.png"))); // NOI18N
        jLabel100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel100MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnun4Layout = new javax.swing.GroupLayout(jPanelAnun4);
        jPanelAnun4.setLayout(jPanelAnun4Layout);
        jPanelAnun4Layout.setHorizontalGroup(
            jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun4Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun4Layout.createSequentialGroup()
                        .addComponent(jLabel91)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun4Layout.createSequentialGroup()
                        .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel97)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel93)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel98)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanelAnun4Layout.createSequentialGroup()
                .addGroup(jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnun4Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel90))
                    .addGroup(jPanelAnun4Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel100)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnun4Layout.createSequentialGroup()
                    .addContainerGap(836, Short.MAX_VALUE)
                    .addComponent(jLabel92)
                    .addGap(36, 36, 36)))
        );
        jPanelAnun4Layout.setVerticalGroup(
            jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnun4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel100)
                .addGap(22, 22, 22)
                .addGroup(jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel97)
                    .addComponent(jLabel98)
                    .addComponent(jLabel99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanelAnun4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnun4Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel92)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel16.add(jPanelAnun4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1270, 1000, 230));

        jlabelTxt.setText("jLabel4");
        jPanel16.add(jlabelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 830, 510));

        jScrollPaneInfo.setViewportView(jPanel16);

        jTabbedPane1.addTab("tab3", jScrollPaneInfo);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 1010, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReservaMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1); 
    }//GEN-LAST:event_jPanelReservaMouseClicked
    private void jPanelReservaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReservaMouseMoved
       //jPanel4.setBackground(new Color(155, 242, 234));
        jPanelReserva.setBackground(new Color(65, 191, 179));
    }//GEN-LAST:event_jPanelReservaMouseMoved
    private void jPanelReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReservaMouseEntered
        // TODO add your handling code here:
        //jPanel4.setBackground(new Color(155, 242, 234));
    }//GEN-LAST:event_jPanelReservaMouseEntered
    private void jPanelReservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReservaMouseExited
        // TODO add your handling code here:
        jPanelReserva.setBackground(new Color(42,140,130)); 
    }//GEN-LAST:event_jPanelReservaMouseExited
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel3MouseClicked
    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(65, 191, 179));
    }//GEN-LAST:event_jPanel3MouseMoved
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(42,140,130));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        try {
        // La URL 
        URI uri = new URI("https://www.instagram.com/itzel_ortix/");   
        // Abrir la URL 
        Desktop.getDesktop().browse(uri);
    } catch (Exception e) {
        // Manejar cualquier excepción que pueda ocurrir al abrir la URL
        e.printStackTrace();
    }
    }//GEN-LAST:event_jLabel25MouseClicked
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel13MouseClicked
    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      //buscarVuelos();
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void cbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrigenActionPerformed
    private void cbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinoActionPerformed

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel50MouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        //actualizarEtiquetas();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnSiguienteActionPerformed
    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved
        // TODO add your handling code here:
        jPanel14.setBackground(new Color(65, 191, 179));
    }//GEN-LAST:event_jPanel14MouseMoved
    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        //Admin
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jPanel14MouseClicked
    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        // TODO add your handling code here:
        jPanel14.setBackground(new Color(42,140,130));
    }//GEN-LAST:event_jPanel14MouseExited
    private void jLabel89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel89MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel89MouseClicked
    private void btnCrudUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudUsActionPerformed
        // TODO add your handling code here:  
        mainUsuarios crudMvcInstance = new mainUsuarios(); 
    // Llamar al método crudus() utilizando la instancia creada
    crudMvcInstance.crudus();
    }//GEN-LAST:event_btnCrudUsActionPerformed

    private void btnCrudVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrudVuelosActionPerformed

    private void btnCrudVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrudVuelosMouseClicked
        // TODO add your handling code here:
        mainVuelos crudMvcInstance = new mainVuelos();   
    // Llamar al método crudus() utilizando la instancia creada
    crudMvcInstance.crudus();
    }//GEN-LAST:event_btnCrudVuelosMouseClicked
    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void jLabel100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel100MouseClicked

    private void jLabelqnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelqnMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jLabelqnMouseClicked

    public void administrador(){
        jPanel14.setVisible(true);
    }
    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        // Cerrar la ventana actual
    dispose(); // Cierra la ventana actual
    // Abrir la nueva ventana de inicio de sesión
    //VistaLogin.();
    VistaLogin vistaLogin = new VistaLogin();
    vistaLogin.setVisible(true);       
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void cboAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAsientosActionPerformed
        // TODO add your handling code here:
       // int asientoSeleccionado=(int) cboAsientos.getSelectedItem();
       // lblAsiento.setText(""+asientoSeleccionado);
    }//GEN-LAST:event_cboAsientosActionPerformed

    private void btnMostrarGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGraficosActionPerformed
        // TODO add your handling code here:
        //mostrarGrafico();
    }//GEN-LAST:event_btnMostrarGraficosActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnCancelarActionPerformed
   
   
    // Agrega un listener a la tabla vuelos para detectar si cambio en selección de este
        private void agregarListenerTabla() {
            // Añade un ListSelectionListener a la tabla
            tablaVuelos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    // Verifica si la selección no está siendo ajustada y si hay una fila seleccionada en la tabla
                    if (!event.getValueIsAdjusting() && tablaVuelos.getSelectedRow() != -1) {
                        btnSiguiente.setEnabled(true);
                    }
                }
            });
        }

    private void customizeButton(JButton button) {
        // Color de fondo
        button.setBackground(new Color(60, 63, 65));
        // Color del texto
        button.setForeground(Color.WHITE);
        // Fuente y tamaño del texto
        button.setFont(new Font("Arial", Font.BOLD, 14));
        // Desactiva el resaltado cuando está enfocado
        button.setFocusPainted(false);
        // Establece un borde vacío para dar espacio alrededor del texto
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
    }
    // Método para actualizar etiquetas
    public void actualizarEtiquetas(String vuelo, String origen, String destino, String fecha, String hora) {
        lblVuelo.setText(vuelo);
        lblOrigen2.setText(origen);
        lblDestino2.setText(destino);
        lblFecha2.setText(fecha);
        lblHora2.setText(hora);
    }

    // Método para rellenar combo box de asientos disponibles
    public void rellenarAsientos(List<Integer> asientosDisponibles) {
        cboAsientos.removeAllItems();
        for (Integer asiento : asientosDisponibles) {
            cboAsientos.addItem(asiento);
        }
    }
    // Método para rellenar boleto
    public void rellenarBoleto(String nombre, String apellidos) {
        lblNombre.setText(nombre);
        lblApellidos.setText(apellidos);
    }
    // Método para etiquetar usuario
    public void etiquedaUs(String nombre) {
        jLabelUs.setText(nombre);
    }
    // Método para mostrar gráfico
  // Muestra el gráfico en un JFrame
    public void mostrarGrafico(JFreeChart barChart) {
        // Crea un panel para el gráfico
        ChartPanel chartPanel = new ChartPanel(barChart);
        // Establece las dimensiones 
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        // Crea un nuevo JFrame para el gráfico
        JFrame chartFrame = new JFrame("Ventas por Vuelo");
        //botón de cierre
        chartFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Agrega el panel del gráfico
        chartFrame.getContentPane().add(chartPanel, BorderLayout.CENTER);
        // Ajusta 
        chartFrame.pack();
        chartFrame.setLocationRelativeTo(null);
        chartFrame.setVisible(true);
    }

    public void agregarListenerBotonMostrarGraficoPorMes(ActionListener listener) {
        btnMostrarGraficoPorMes.addActionListener(listener);
    }

    public int obtenerMesSeleccionado() {
        return cboMes.getSelectedIndex() + 1; // Los índices de JComboBox empiezan en 0, sumamos 1 para obtener el mes correcto
    }

    // Método para agregar listener a la tabla
    public void agregarListenerTabla(ListSelectionListener listener) {
        tablaVuelos.getSelectionModel().addListSelectionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPag().setVisible(true);
                //new panel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrudUs;
    private javax.swing.JButton btnCrudVuelos;
    public javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMostrarGraficoPorMes;
    public javax.swing.JButton btnMostrarGraficos;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JComboBox<String> cbDestino;
    public javax.swing.JComboBox<String> cbOrigen;
    public javax.swing.JComboBox<Integer> cboAsientos;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    public javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelUs;
    public javax.swing.JLabel jLabelqn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAnun;
    private javax.swing.JPanel jPanelAnun1;
    private javax.swing.JPanel jPanelAnun2;
    private javax.swing.JPanel jPanelAnun3;
    private javax.swing.JPanel jPanelAnun4;
    public javax.swing.JPanel jPanelReserva;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneAdmin;
    private javax.swing.JScrollPane jScrollPaneBoleto;
    private javax.swing.JScrollPane jScrollPaneInfo;
    private javax.swing.JScrollPane jScrollPanePublicidad;
    private javax.swing.JScrollPane jScrollPaneReserva;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel jlabelTxt;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblDestino;
    public javax.swing.JLabel lblDestino2;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblFecha2;
    public javax.swing.JLabel lblHora;
    public javax.swing.JLabel lblHora2;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblOrigen;
    public javax.swing.JLabel lblOrigen2;
    public javax.swing.JLabel lblVuelo;
    public javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables

   
}
